---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "5000"
  USER_SERVICE_URL: "5001"
  TUTOR_SERVICE_PORT: "5002"
  COURSE_SERVICE_PORT: "5004"
  AUTH_GRPC_PORT: "5005"
  ADMIN_SERVICE_PORT: "5006"
  PAYMENT_SERVICE_PORT: "5007"
  ORDER_SERVICE_PORT: "5008"
  CHAT_SERVICE_PORT: "5009"
  TRANSCODER_SERVICE_PORT: "5010"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
type: Opaque
data:
  JWT_SECRET: Njc3ZjM4ODJhN2E3ZWZjM2Q3MGI4OTZiOThjMTE1NDc0ZmE3YjBlNDRmMDdiMTgyODdkNWI2Yjg0ZjI3NjEwNGExNDE4MGFmMTUyOTNjZWNlMzQxN2M5YmU1NTkzMDFkNGZkYmU5MjU2YzJiMzdlNDkzMjRkMGZkNzBiYmIyNTk=
  REFRESH_TOKEN_SECRET: Njc3ZjM4ODJhN2E3ZWZjM2Q3MGI4OTZiOThjMTE1NDc0ZmE3YjBlNDRmMDdiMTgyODdkNWI2Yjg0ZmExNDE4MGFmMTUyOTNjZWNlMzQxN2M5YmU1NTkzMDFkNGZkYmU5MjU2YzJiSkZJRFNKVklEWUdJRFdPMzgzOTU3MzY0ODM5Mg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: api-gateway-config
        - secretRef:
            name: api-gateway-secrets
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: api-gateway